### ISSUE TITLE
vertexmatrix method doesn't care about inputs

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#101]
**Describe the bug**
Don't know if this is a bug, but the `vertexmatrix` method for the mesh doesn't raise any error upon providing an argument (I think the default required arguments are 0)

**To Reproduce**
```
import meshtools

var m = LineMesh(fn (t) [t,0,0], -1..1:0.1)

print m.vertexmatrix() // Normal output
print m.vertexmatrix(0) // still normal output
print m.vertexmatrix(325235) // still normal output
print m.vertexmatrix(a=25) // still normal output

var s = Selection(m, fn(x,y,z) abs(x)<0.5)
print m.vertexmatrix(selection=s) // still normal output
```

**Expected behavior**

InvldArgs error

**Comment by softmattertheory** [comment]
Morpho builtins are, for now, very forgiving about arguments. We generally only return an error if the arguments are demonstrably *wrong*. So this isn't a bug. [We may tighten this policy in the future].
