### ISSUE TITLE
[Bug] for range is not iterating though last step

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#105]
**Describe the bug**
for (v in 0.1..2:0.1) print v

![image (1)](https://user-images.githubusercontent.com/88550879/156646535-b1c995bf-b9d0-4bea-85d1-45c525f46da4.png)

it is missing the last value

**Comment by softmattertheory** [comment]
This is subtle, because `for (t in 0..1:0.1) print t` works!
