### ISSUE TITLE
[Bug] Segfault upon incorrect assginment in function call

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#110]
**Describe the bug**
A typo in the constructor for `FloryHuggins` results in a segfault

**To Reproduce**
```
var m = Mesh("tetrahedron.mesh") // Can be found under test/functionals/floryhuggins

var mref = m.clone()

var lfh = FloryHuggins(mref. // This "." should be a ","
    a = 1.0,
    b = 1.0,
    c = 1.0,
    phi0=0.5
)

print lfh
```

**Expected behavior**
Some error indicating that the period is incorrect

**Comment by ConduitDan** [comment]
This segfaults in program_bindobject in vm/vim.c:100 obj it in invalid pointer
We should probably catch this as a parse error before this happens as mref. is not valid.

**Comment by ConduitDan** [comment]
Assignment in fn call
