### ISSUE TITLE
[Bug] Incorrect creation of lists out of member matrices

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#112]
**Describe the bug**
When creating a list out of matrices that belong to the class, the result is unexpected.

**To Reproduce**
Run the following program:
```
class Test {
    init() {
        
        // This works

        var x = Matrix([1,2,3])

        self.lstx = [ x[0], x[1], x[2] ]
        print self.lstx // We get [ 1, 2, 3 ]

        // *** This doesn't work ***

        self.y = Matrix([1,2,3])

        self.lsty = [ self.y[0], self.y[1], self.y[2] ]
        print self.lsty // We get [ 3, 3, 2 ] instead of [ 1, 2, 3 ] !
        
        // They individually work fine
        print self.y[0] // We get 1
        print self.y[1] // We get 2
        print self.y[2] // We get 3

        // This works too
        self.a = 1
        self.b = 2
        self.c = 3
        self.lstz = [self.a, self.b, self.c]
        print self.lstz  // We get [ 1, 2, 3 ]

    }
    
}

var t = Test()

```

**Additional context**
In other cases, I have also gotten `[ 0, 0, false ]` or `[ -0.00598557, -0.00598557, mulr ]` as the outputs for `print self.lsty`, when the matrix y was a column of a vertexmatrix of the mesh. I can add in those minimal examples too if needed.

**Comment by softmattertheory** [comment]
This looks to be a register allocation issue in the compiler. Disassembling the line where the list is created: 

    33 : lct r2, c1               ; c1=<fn List> 
    34 : lpr r3, r0, c7           ; c7=y
    35 : lct r4, c5               ; c5=0 
    36 : lix r3, r4, r4           ; 
    37 : mov r3, r4               ; 
    38 : lpr r3, r0, c7           ; c7=y
    39 : lct r4, c2               ; c2=1 
    40 : lix r3, r4, r4           ; 
    41 : mov r3, r4               ; 
    42 : lpr r3, r0, c7           ; c7=y
    43 : lct r4, c3               ; c3=2 
    44 : lix r3, r4, r4           ; 
    45 : mov r3, r4               ; 
    46 : call r2, 3               ; 

showing that the compiler is repeatedly storing the elements of the list in r3; r4,5 contain garbage values.
