### ISSUE TITLE
[Task] Nanboxing test failures

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#118]
With nanboxing turned off two tests fail,
in logical/or_truth.morpho 
`print "s" or "ok" // expect: s` prints ok

in if/truth.morpho
`if ("") print "empty" // expect: empty` doesn't print anything

**Comment by ConduitDan** [comment]
These are both quite tricky to track down, running with GDB doesn't produce the error

**Comment by softmattertheory** [comment]
I also can't reproduce these. For the first one, the disassembly is this. So nothing here is being garbage collected, but perhaps something has been mangled in the constant table... 

    16 : lct r0, c5               ; c5=s 
    17 : bif t r0 1
    18 : lct r0, c1               ; c1=ok 
    19 : print r0

**Comment by softmattertheory** [comment]
Which platform is this occurring on? Have we tried running with valgrind?

**Comment by softmattertheory** [comment]
The second test [if/truth] definitely has something fishy going on. On macOS we're getting: 

    14 : lct r0, c6               ; c6= 
    15 : bif f r0 1
    16 : print c7                 ; c7=empty 
    17 : end 

but on Ubuntu we're missing instruction 16 for some reason. But constant 6 should be "empty" in any case... So something is weird. I'll investigate further...
