### ISSUE TITLE
[Bug] Disk mesh from meshgen breaks the tactoid example

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#119]
2D mesh generated using meshgen has a vertex matrix of dimension [2,N] as opposed to [3,N]. This results in a `MtrxIncmptbl` error at optimize.morpho:243 while running the conjugategradient function. 

**To Reproduce**
1. Go to examples/tactoid/tactoid.morpho
2. Replace `var m = Mesh("disk.mesh")` with the following:
```
import meshgen
// Domain composed of a single disk
var dom = fn (x) -(x[0]^2+x[1]^2-1)
var mg = MeshGen(dom, [-1..1:0.2, -1..1:0.2], quiet=false)
var m = mg.build()
```
3. Run the example.

**Comment by softmattertheory** [comment]
This is known and I am adding something to MeshTools to enable the user to easily change the dimensionality of the mesh.

**Comment by softmattertheory** [comment]
Fixed
