### ISSUE TITLE
[Bug] waring in morphoview install

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#137]
Encountered on WSL

**Comment by softmattertheory** [comment]
@ConduitDan  Can you include the Warning?

**Comment by SteveWufeng** [comment]
Reproduce the bug:
In WSL, 
under morpho/morphoview/ directory
run 
>> sudo make -f Makefile.linux install

Screen shot
![image](https://user-images.githubusercontent.com/86623538/173594690-54ffdfa2-bc47-4e85-a97e-febd071ba312.png)

**Comment by softmattertheory** [comment]
Fixed in 0.5.4
