### ISSUE TITLE
[Bug] windows does not resize correctly

### ISSUE THREAD

**Issue by SteveWufeng** [Morpho-lang/morpho#141]
**Describe the bug**
Morphoview window does not resize/update the view correctly when the window change.

**To Reproduce**
1. Go to 'morpho/examples/cube'
2. Run the example morpho file 'morpho5 cube.morpho'
3. Resize the window.
4. notice the error.

**Expected behavior**
The field of view in the window is supposed to update based on the resolution of the window. enlarge the field of view and show the objects.

**Screenshots**
![image](https://user-images.githubusercontent.com/86623538/173416551-ff01f579-bd23-47d0-8675-7a1e705eabd3.png)
![image](https://user-images.githubusercontent.com/86623538/173416629-73eb9786-a79a-451c-9151-2d55a59eef13.png)
![image](https://user-images.githubusercontent.com/86623538/173416672-af80f44c-ab73-4c67-8de9-80398a0607c5.png)
![image](https://user-images.githubusercontent.com/86623538/173417120-61ff4c32-61fa-4af4-a84b-7374082d08ce.png)

**Additional context**
This would not be a critical issue when the mesh is small and can fit in the scope, but this will be a critical problem when the mesh is larger than the scope of view.

**Comment by softmattertheory** [comment]
Thanks to @tussmm for fixing this!
