### ISSUE TITLE
[Bug] Trying to catch from a varible results in consistency error 

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#143]
var err = Error("Foo", "A Foo occurred")
var str = "Foo"
try {
  err.throw()
} catch {
  str:
    print "Caught the foo" // expect: Caught the foo
    print "(boohoo)" // expect: (boohoo)

}
Internal consistency error: Please contact developer. [Explanation: Not a string!].

**Comment by ConduitDan** [comment]
Looks like at compile.c:2095 we have no handling for if a label is not a string

**Comment by softmattertheory** [comment]
Fixed!
