### ISSUE TITLE
[Bug] Small Documentation Error

### ISSUE THREAD

**Issue by EmHamilton** [Morpho-lang/morpho#145]
**Describe the bug**
On page 40 of the documentation pdf (6.17 Sets) the code given to generate all sets of order n from a list is given as "var t = [ 1, 2, 3 ].tuples(2)" which is identical code as given in 6.16 Tuples to give all tuples from a given list. Likely all that would need to be changed is updating the example code.

**Comment by softmattertheory** [comment]
Fixed in 0.5.4
