### ISSUE TITLE
[Bug] Class Defined in another classes method gains subsequent methods

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#146]
class one {
    
    method1() {
        class two {
            methodA() {
                return true
            }
        }
        var newclass = two()
        print newclass.respondsto("method2")
    }
    method2() {
        return true
    }
} 
one().method1()

**Comment by softmattertheory** [comment]
Nested classes, for now, should simply be forbidden. There needs to be something like a closure, but for classes, to allow it. 

I'll add in an error when the compiler encounters this.

**Comment by softmattertheory** [comment]
Fixed in 0.5.4, although does so by forbidding nested classes. We could reopen this if we can see a use case for them.
