### ISSUE TITLE
[Bug] Issue with meshmerge

### ISSUE THREAD

**Issue by EmHamilton** [Morpho-lang/morpho#149]
**Describe the bug**
MesMerge does not eliminate duplicate edges when combining meshes. 

**To Reproduce**
import meshtools
import meshgen

var m1 = MeshBuilder()
var m2 = MeshBuilder()

m1.addvertex([0,0,0])
m1.addvertex([0, 1, 0])
m1.addvertex([0,1,-1])
m1.addedge([0,1])
m1.addedge([1,2])
m1.addedge([2,0])

m2.addvertex([0,0,0])
m2.addvertex([0, 1, 0])
m2.addvertex([0,1,1])
m2.addedge([0,1])
m2.addedge([1,2])
m2.addedge([2,0])

var mesh1 = m1.build()
var mesh2 = m2.build()
var merge = MeshMerge([mesh1])
merge.addmesh([mesh2])
var disk = merge.merge()
disk.save("testing.mesh")

The mesh generated by this code has 2 edges connecting vertices (0,0,0) and (0,1,0). 

**Expected behavior**
When merging the meshes, duplicate edges should be eliminated

**Comment by softmattertheory** [comment]
Fixed for 0.5.4
