### ISSUE TITLE
[Bug] Hydrogel refactor

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#174]
The Hydrogel speedup update to dev (#171) has an implementation of hydrogel_gradient assumes volume elements, which means the hydrogel functional currently wouldn't work in 2D. The idea is to have a functional_elementgradient method that would pick out the correct (area vs volume etc) gradient method, making such applications grade-independent.

Note that the existing Hydrogel gradient on the 0.5.4 release should work just fine.

**Comment by softmattertheory** [comment]
@joshichaitanya3  Can you check this works on the latest /dev branch? If so, I'll close the issue.

**Comment by joshichaitanya3** [comment]
All tests are passing on the latest dev!

**Comment by softmattertheory** [comment]
Amazing, we can close this!
