### ISSUE TITLE
[Documentation] Need instructions on how to update existing Morpho installation

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#210]
Updating Morpho currently requires performing a `git pull` operation in the Morpho directory followed by installation. These steps aren't documented in the current README.md

**Comment by softmattertheory** [comment]
This is a really great suggestion, @joshichaitanya3! I'm going to update the README.md file before the next release to include information about updating morpho. We should probably include this in the manual.

**Comment by softmattertheory** [comment]
I've added this to the manual!
