### ISSUE TITLE
As far as development go?

### ISSUE THREAD

**Issue by eihabhala** [Morpho-lang/morpho#219]
I were spending more than ten hours straight reading about this wonderful language it compares much better than R module Morpho and it's well capable as far as development go, where to find packages or Libraries for the language. And how to expand it once I have a C language library?

**Comment by softmattertheory** [comment]
Hey @eihabhala, thanks for the kind feedback and sorry for the slow response! We're in the process of building out the morpho ecosystem, so check in the Morpho-lang organization to see some of the extensions and packages under development. Are you interested in particular libraries? 

You may also be interested in checking out the dev-guide which talks a bit more on how to extend morpho with C packages (or any other language that links to C). 

Finally, consider joining the morpho Slack community: https://join.slack.com/t/morphoco/shared_invite/zt-1o6azavwl-XMtjjFwxW~P6C8rc~YbBlA

**Comment by softmattertheory** [comment]
I'm closing this since there's no action to be taken. Please feel free to reach out @eihabhala with suggestions, questions or feedback!

**Comment by eihabhala** [comment]
Thanks have joined the group
