### ISSUE TITLE
ScalarPotential Help Documentation out of date 

### ISSUE THREAD

**Issue by Craftyleosteel** [Morpho-lang/morpho#229]
**Describe the bug**
Inaccurate description of ScalarPotential in the documentation. Now, ScalarPotential can be initialized without gradient and can be done only with a function. ScalarPotential then numerically calculates the gradient (check #84). However, the help says it requires two functions

**Comment by softmattertheory** [comment]
Thanks for this feedback, @Craftyleosteel; I'll update the documentation.

**Comment by softmattertheory** [comment]
I've now updated the documentation and the correct specification for ScalarPotential is fixed by #232 and will be available in 0.5.7
