### ISSUE TITLE
Mistake in the hyperlink for windows download steps

### ISSUE THREAD

**Issue by Craftyleosteel** [Morpho-lang/morpho#236]
In the downloading morpho section of the main read me the hyperlink to the Windows downloading component is not updated. If the hyperlink could be fixed it would improve the user experience for windows users.

**Comment by Craftyleosteel** [comment]
Also maybe note that if they want to update to WSL2 they should uninstall WSL1

**Comment by softmattertheory** [comment]
We've updated Windows installation instructions in the forthcoming v0.6.0 releast, which are now much simpler. Thanks for raising this @Craftyleosteel !
