### ISSUE TITLE
[Bug] Apt install instructions not working

### ISSUE THREAD

**Issue by Polidori-112** [Morpho-lang/morpho#251]
**Describe the bug**
Instructions tell us to apt-get install the liblapacke library, however the liblapacke-dev library is needed to get the proper header files in order to properly install.

**To Reproduce**
1. Open up Ubuntu or Debian based system
2. Copy-paste install instructions
3. See that cmake and sudo make install both fail due to liblapacke.h not being installed

**Additional context**
After sudo apt install liblapacke-dev, I can cmake and install properly, so simply updating the install instructions with the proper library should fix this issue

**Comment by softmattertheory** [comment]
Many thanks for this feedback, @Polidori-112! We will fix the error in the installation instructions shortly.

**Comment by softmattertheory** [comment]
The installation instructions are now fixed. Thanks again @Polidori-112 for helping us fix this error.
