### ISSUE TITLE
[Bug] Examples workflow incorrectly passes

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#263]
**Describe the bug**
`examples.py` doesn’t catch for the case when it cannot run the morpho file itself, as is happening right now since the command is `morpho5`. So no examples are run, but it reports all passing. While changing it to `morpho6` should do the trick for now, it would be great to catch and report this locally or through the CI.

P.S. The examples.py is currently passing all tests if run with `morpho6` on my machine!

**Comment by softmattertheory** [comment]
Thanks for this @joshichaitanya3 ! We will fix this as we work on the 0.6.1 release.

**Comment by softmattertheory** [comment]
Thanks again for noting this, @joshichaitanya3; we've now fixed this in PR #276.
