### ISSUE TITLE
[Bug] Initializing MeshMerge without a list fails silently 

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#31]
**Describe the bug**
If the `MeshMerge` object is initialized with just a mesh (like `var merger = MeshMerge(m)`) instead of a list (like `var merger = MeshMerge([m])`), then the final object doesn't contain the initial mesh, and the code runs with no error.

**To Reproduce**
`import meshtools`
`import plot`
`var m1 = LineMesh(fn (t) [t,0,0], 0..1:0.2) // Straight line along x axis`
`var m2 = LineMesh(fn (t) [0,t,0], 0..1:0.2) // Straight line along y axis` 
`var merger = MeshMerge(m1)`
`merger.addmesh([m2])`
`var mf = merger.merge()`
`Show(plotmesh(mf))`

**Expected behavior**
![image](https://user-images.githubusercontent.com/16670570/139134465-cb67b8bf-8510-4694-80b7-8cf5ceb8341d.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/16670570/139134557-db42db72-7127-4bd4-b0b2-f0adfd7d1208.png)

**Note**
This code works even if `[m2]` is  replaced with `m2`. The additional mesh didn't have to be a list.
Also, a simplified version as follows also works:
`var merger = MeshMerge([m1,m2])`
`var mf = merger.merge()`

**Comment by ConduitDan** [comment]
Hmmm I tried to solve this by adding list wrapers to the init but its then apearing as a <fn List>

still working on it
