### ISSUE TITLE
[Bug] Trying to plot a mesh with only two components generates `MtrxBnds': Matrix index out of bounds.` error

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#33]
**Describe the bug**
If we give a 2D vector to the mesh constructor, it throws a  `MtrxBnds': Matrix index out of bounds.` error, where instead, it should either silently generate a 2D mesh setting z=0 or give an error asking for a 3D vector explicitly.

**To Reproduce**
`import meshtools`
`import plot`
`var m1 = LineMesh(fn (t) [cos(t),sin(t)], 0..2*Pi:0.1*Pi) // As opposed to  [cos(t),sin(t),0]`
`Show(plotmesh(m1))`

**Comment by ConduitDan** [comment]
This looks like an issue with morphoview.
The normalvector function called by totrianglecomplex expects a 3x1 matrix but in this case it only gets a 2x1 matrix

Perhaps the viewer should do some pre-conditioning on its meshes to prep them for plotting

**Comment by softmattertheory** [comment]
What's the status of this? If the problem is in morphoview, we should make sure that the graphics module doesn't try to send 2D information to morphoview...

**Comment by ConduitDan** [comment]
Ok, would this some argument checking in the 'Show' class? and is there an easy way to matrix concatenate?

**Comment by softmattertheory** [comment]
I think it has to be earlier in the Graphics system... i.e. in plotmesh...

**Comment by softmattertheory** [comment]
Looking at the error message: 

Error 'MtrxBnds': Matrix index out of bounds.
    in normalvector at line 28
  from totrianglecomplex at line 150
  from view at line 111
  from write at line 582
  from init at line 570
  from global at line 1

The error is occuring in the graphics library, but I think the fix is to ensure plot mesh promotes 2-vectors to 3-vectors. I can work on this if you didn't already start @ConduitDan

**Comment by ConduitDan** [comment]
I just did some digging no actual fixing yet. I've taken myself off

**Comment by softmattertheory** [comment]
This has been fixed at some point, definitely works in 0.5.4!
