### ISSUE TITLE
[Bug]:[cant add lines to 2D mesh]

### ISSUE THREAD

**Issue by ancaandrei** [Morpho-lang/morpho#34]
**Describe the bug**
Error 'MshAddGrdOutOfBnds': Cannot add elements of grade 1 to mesh with max grade 2
    in global at line 10

**To Reproduce**
1. Go to '../morpho/examples/cholesteric/cholesteric.morpho'
2. Change [u,v,0] in line 9 to [u,v]
3. In terminal, run morpho5 cholesteric.morpho
4. See error shown in description. 

**Expected behavior**

**Screenshots**
NA
**Additional context**
NA

**Comment by ConduitDan** [comment]
addGrade wasn't check all the way up to the max allowable grade it could add.
