### ISSUE TITLE
[Bug] Segfault involving `Mesh()` 

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#39]
**Describe the bug**
There are two related bugs:
1. If the `Mesh` constructor is initialized with nothing, like `var m = Mesh()`, then at least some operations on this object result in segfault (see below)
2. If the `Mesh` constructor is initialized with an existing mesh, like `var m2 = Mesh(m)`, then it creates an empty mesh like above, resulting in the same behavior.

**To Reproduce**
Run the following code:
`import meshtools`
`var m = Mesh()`
`print m // shows empty mesh` 
`m.setvertexposition(0, Matrix([-5,0,0])) // Segfaults`

or

`var m = LineMesh(fn (t) [t,0,0], -1..1:0.2)`
`m.setvertexposition(0, Matrix([-5,0,0])) // works`
`var m2 = Mesh(m)`
`print m2 // shows empty mesh` 
`m2.setvertexposition(0, Matrix([-5,0,0])) // Segfaults`

**Expected behavior**
In the case of empty mesh, maybe an error message? In the case of initializing with another mesh, perhaps an output of the deepcopy of the input mesh would make sense.

**Screenshots**
![image](https://user-images.githubusercontent.com/16670570/139310439-63e10e38-ea04-4927-8b5a-5f1e83460b98.png)

**Comment by ConduitDan** [comment]
Fixed by #40
