### ISSUE TITLE
Q-tensor example clean up

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#45]
The Q-tensor needs some clean up see #42 for comments

**Comment by joshichaitanya3** [comment]
Working on it! Thanks for the detailed comments and feedback! I will probably do this in stages, the code first and the write-up later. Let me know if that works, else I'll just hold the pull request till I am done with everything.

**Comment by softmattertheory** [comment]
I also note that disk.mesh is missing from the folder... We should probably include that too!

**Comment by ConduitDan** [comment]
@softmattertheory I was thinking we could include some standard meshes on the path so that we don't need to have many copies of them floating around.

A few prebuilt meshes accessible from anywhere would be nice :-)

**Comment by ConduitDan** [comment]
> Working on it! Thanks for the detailed comments and feedback! I will probably do this in stages, the code first and the write-up later. Let me know if that works, else I'll just hold the pull request till I am done with everything.

sounds good.
Check out 
https://github.com/Morpho-lang/morpho/blob/a5e93616c26cd301dc339f8bd8bc87ddee962a8d/examples/thomson/thomson.morpho

for an example that Tim and I commented together

**Comment by softmattertheory** [comment]
What's the status on this one @joshichaitanya3  and @ConduitDan?

**Comment by joshichaitanya3** [comment]
I should be done with the code edits today. We can discuss what we want to do with the PDF.

**Comment by joshichaitanya3** [comment]
Alright, I am ready to update the code. I like @ConduitDan's idea of including some standard meshes on the path. To that end, should I be adding the "disk.mesh" to this directory?

**Comment by ConduitDan** [comment]
I think for now add it to the folder and we can work on adding the meshes to the path in the future

**Comment by softmattertheory** [comment]
Was this fixed by pull request #57?

**Comment by joshichaitanya3** [comment]
I still haven't updated the PDF, so #57 still remains open, I think.

**Comment by softmattertheory** [comment]
I'm going to close this issue, because it's now really part of the examples cleanup we should do for 0.6.
