### ISSUE TITLE
[Question] Adding grade 0 to the mesh results in the failure of the equielement.morpho test

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#50]
Adding 
`m.addgrade(0)`
to line 7 of [equielement.morpho](https://github.com/Morpho-lang/morpho/blob/main/test/functionals/equielement/equielement.morpho) results in the failure of the test, specifically in the `gradient`, and hence the optimization.

 Here is a screenshot of before and after:
![image](https://user-images.githubusercontent.com/16670570/140660974-c31dc74d-5805-4c18-bcaf-5bbb3beb9cc8.png)

I am not sure whether this is a bug or my lack of understanding of how `EquiElement` works. I was having some issue with EquiElement in a separate code, which is why I dug into the test example. While trying to visualize the vertices by adding grade 0 elements, the test failed and the vertex positions were quite off (`[ 8.02753 4.31376 3.00688 ]` as opposed to `[ 0 0.500034 1 ]`).

**Comment by softmattertheory** [comment]
This is very strange. Trying to add grade 0 to a mesh should yield no change, because all meshes are required to have grade 0! I'll take a look...
