### ISSUE TITLE
[Feature Request] Incorporate CMake for portable builds

### ISSUE THREAD

**Issue by mattsep** [Morpho-lang/morpho#61]
I think it would be worth having the option to use CMake for building Morpho. This might make it easier for new users to get up and running without needing to worry (too much) about whether they're using the right linker flags for the various dependencies, regardless of the system they're running. This has the potential to also make Windows builds easier, though that will need some testing.

I have a minimal working example that can compile on my Linux system, but I'll need to do some more testing before I make a PR. The goal of this Issue is to have a place to discuss what needs to go into making this happen, as well as to discuss other relevant aspects of the build process.

**Comment by mattsep** [comment]
One aspect of the build process that I think can be cleaned up with this change is that currently users must change values in the Makefile and in `morpho5/build.h` in order to have a self-consistent installation. For example, if I change the installation prefix in the Makefile to `$HOME/.local`, but forget to change the value of `MORPHO_MODULEDIRECTORY`, then I won't be able to import modules because they won't be on the search path.

I think the cleanest way to resolve this is to wrap the various configuration variables:
```cpp
// morpho5/build.h

#ifndef MORPHO_MODULEDIRECTORY
#define MORPHO_MODULEDIRECTORY "/usr/local/share/morpho/modules"
#endif

// ... and so on for the other variables
```
Doing so would mean that `build.h` provides a set of sensible defaults that are easily overridden with an appropriate argument passed to the compiler. We can then modify the Makefile (or CMakeLists.txt file) to pass along user-overridden options to the compiler.

Does this seem like a reasonable approach?

**Comment by softmattertheory** [comment]
I have fantastic news @mattsep; for our forthcoming v0.6.0 we have transitioned entirely to CMake. Thanks for this amazing suggestions; it's taken a while but it's here and has enabled a much smoother cross-platform experience.
