### ISSUE TITLE
[Bug] Typo Fixes

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#64]
1.  In README.md, the formatting of the Linux / Mac commands (indented text) is different than that of the WSL commands (code blocks). It'd be nice to make it consistent (I am fine with either, but have a slight preference for the code block as you get a copy-to-clipboard button next to those).
2.  In the acknowledgements section of the manual, Matthew Peterson's first name needs one more 't' :)

**Comment by softmattertheory** [comment]
I think we should use a different tag for this, such as documentation?
