### ISSUE TITLE
[Bug] print doesn't differentiate between 2 and "2"

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#67]
**Describe the bug**
print "2" and print 2 both output 2 
print [2,"2"]  gives [2,2]

var a = [2,"2"]
>print a[0]+a[1]
Error 'InvldOp': Invalid operands. Failed to Add 2 and 2

this is confusing

**Comment by softmattertheory** [comment]
But then print "Hello World" prints

"Hello World" 

as expected!

**Comment by ConduitDan** [comment]
Yup! my mistake this is the expected behavior.

Closing this issue. Though perhaps a improvement on the invalid op error could be to report the type.

**Comment by softmattertheory** [comment]
I think something to think about is whether displaying elements of a list is fundamentally different from displaying a single string. I can see 

[ 1, "1" ]

being useful... 

Or perhaps, offer different formatting options. Of course this is why print() is a function in python...
