### ISSUE TITLE
Typos in manual 

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#68]
From Saul Sun

Typos in manual

    usage of '''code''' font is not consistent thought manual
    4.9 "el.update(refmap) // Update the problem" Indentation
    5.8 Peren instead of brakets
    5.13 use code font for first IF
    5.17 space between 1,2 (also use code font for break)
    5.18 1,2 need space
    5.28 input isn't an angle, what is the range? Why use one arguement instead of two
    5.43 should be titled isnan
    6.3 lookup should probably be two words
    6.4 lookup should probably be two words
    6.5 and 6.6 need var
    6.8 what order does it get sorted in also that its in place, provide an example
    7.2 (grade 1) elements vs (grade 2 elements)
    7.4 Additional Field objects may BE supplied
    7.5 import ‘functionals‘ (don't need ')
    7.6 length of a line elements
    7.9 and 7.10 AN
    7.9 "An VolumeEnclosed functional calculates the volume enclosed by a surface of line elements" is unclear and may not be correct
    7.11 level set constraints is not a well known term
    7.18 it might be nice to define what grad of higher d objects are

**Comment by softmattertheory** [comment]
@ConduitDan  I have fixed these and will push—don't worry!
