### ISSUE TITLE
[Bug] for loops with blank bodies 

### ISSUE THREAD

**Issue by softmattertheory** [Morpho-lang/morpho#80]
**Describe the bug**

**To Reproduce**
for (i in 1..2)
  for (j in 1..2)
    print i+j

generates Internal consistency error: Please contact developer. [Explanation: compiling an unexpectedly blank node [run with debugger]].

**Expected behavior**
Should either generate a warning: 
"For loop with blank body" 

Or compile as nested for loop. 

**Additional context**
This is an edge case for semicolon suppression. Normally, morpho accepts an end of line as a semicolon anywhere it would be valid. 

for loops with blank bodies are occasionally useful (tho not for..in loops?)

**Comment by ConduitDan** [comment]
Throw compiler error for blank body

**Comment by softmattertheory** [comment]
Fixed in 0.5.4
