### ISSUE TITLE
[Bug] Segfault while using String split

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#87]
**Describe the bug**
Performing the split operation on strings a bunch of times results in a Segmentation Fault

**To Reproduce**
```
var str = "a b c d e"

var w 

for (i in 1..10) {
    w = str.split(" ")
    print w
}
```
Output:
```
[ a, b, c, d, e ]
[ a, b, c, d, e ]
[ a, b, c, d, e ]
[ a, b, c, d, e ]
Segmentation fault (core dumped)
```

A number of things change the behavior of this segfault, including 
* the length of the initial string, 
* whether or not we print `w`,
* Whether we add a `print "${str}"` before the split 

Here is the `gdb` output with the backtrace:

![image](https://user-images.githubusercontent.com/16670570/154108021-02a4e79e-e6a6-4aed-bfc4-35ef2a7041f5.png)

**Comment by ConduitDan** [comment]
Vm state when slice works well is 

{current = 0x5555555e98b0, globals = {count = 3, capacity = 4, data = 0x5555555ee980}, stack = {count = 7, capacity = 256, data = 0x5555555e9b90}, frame = {{
      function = 0x5555555e9900, closure = 0x0, roffset = 0, pc = 0x5555555eed8c, stackcount = 0, ret = false}, {function = 0x0, closure = 0x0, roffset = 0, pc = 0x0, stackcount = 0, 
      ret = false} <repeats 63 times>}, errorhandlers = {{fp = 0x0, dict = 0} <repeats 64 times>}, instructions = 0x5555555eed60, konst = 0x5555555eee80, fp = 0x5555555ecbf8, ehp = 0x0, 
  err = {cat = ERROR_NONE, id = 0x0, module = 0x0, line = -1, posn = -1, msg = '\000' <repeats 254 times>}, objects = 0x5555555ef460, gray = {graycount = 0, graycapacity = 0, 
    list = 0x0}, bound = 412, nextgc = 1024, debug = false, openupvalues = 0x0}


Vm state in the split call before it fails is:
{current = 0x5555555e98b0, globals = {count = 3, capacity = 16, data = 0x5555555ef8a0}, stack = {count = 7, capacity = 256, data = 0x5555555e9b90}, frame = {{
      function = 0x5555555e9900, closure = 0x0, roffset = 0, pc = 0x5555555eed8c, stackcount = 0, ret = false}, {function = 0x0, closure = 0x0, roffset = 0, pc = 0x0, stackcount = 0, 
      ret = false} <repeats 63 times>}, errorhandlers = {{fp = 0x0, dict = 0} <repeats 64 times>}, instructions = 0x5555555eed60, konst = 0x5555555eee80, fp = 0x5555555ecbf8, ehp = 0x0, 
  err = {cat = ERROR_NONE, id = 0x0, module = 0x0, line = -1, posn = -1, msg = '\000' <repeats 254 times>}, objects = 0x5555555ef860, gray = {graycount = 0, graycapacity = 8, 
    list = 0x5555555eeb30}, bound = 308, nextgc = 616, debug = false, openupvalues = 0x0}

global->capacity changes as does the gray->capacity but i'm not sure if thats relevant

**Comment by softmattertheory** [comment]
This is a GC issue. String.split was calling morpho_bindobjects dangerously, and the gc was missing an important object.
