### ISSUE TITLE
[Bug] Need builtin isinf and isnan

### ISSUE THREAD

**Issue by joshichaitanya3** [Morpho-lang/morpho#9]
**Describe the bug**
Two positive infinities are not treated equal in the code, so there isn't a way to look for `inf` values

**To Reproduce**
`var x = 1/0 // generates inf`
`var y = x + 2 // also generates inf`
`print x==y // Expect true, but get false`

Since this doesn't output `true`, there is no way to look for infinities in a field or another object. Also, since `nan`'s cannot be compared, this method cannot be used to identify `nan`'s.

An inbuilt function `isinf` and also `isnan` would be great to have!

**Comment by softmattertheory** [comment]
I like this idea. @ConduitDan want to try this? Should be pretty easy; follow the templates in builtin.c
