### ISSUE TITLE
[Bug] infinite loop in list.sets()

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#91]
>var A = [1,2,3]
>var B = A.sets(4)
causes morpho to hang followed by being killed :-(

**Comment by softmattertheory** [comment]
Any progress on this?

**Comment by ConduitDan** [comment]
added some argument checking to the set operation 

        if (n>slf->val.capacity) n = slf->val.capacity;

Working on #38 and #77 in one branch, I plan on posting a pull request this afternoon
