### ISSUE TITLE
[Bug] povray quiet mode is not quiet

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#96]
running povray in quiet mode doesn't silence it, instead it run it in a new process

Working on adding minimal example

**Comment by softmattertheory** [comment]
This is working on macOS... the povray module pipes stdout to dev/null as follows: 

    &> /dev/null

I'm guessing this doesn't work on linux..? What's the equivalent?

**Comment by softmattertheory** [comment]
I have finally been able to reproduce this, and it's because of how the redirection to /dev/null was being done. I made a PR that appears to fix the issue.

**Comment by softmattertheory** [comment]
Thanks so much for finding this @ConduitDan!
