### ISSUE TITLE
[Bug] Cannot translate images in morpho view

### ISSUE THREAD

**Issue by ConduitDan** [Morpho-lang/morpho#97]
We need a way to translate images in morphoveiw

**Comment by ConduitDan** [comment]
Clicking back onto an image reorients it

in glfw make sure it doesn't reset when it gets the input focus

**Comment by softmattertheory** [comment]
I think this is more of an `enhancement` than a `bug`.

**Comment by softmattertheory** [comment]
This has been fixed in dev and will arrive in 0.5.4
